### ISSUE TITLE
Use API instead of parsing html

### ISSUE THREAD

**Issue by VictorWinberg** [CookingMonsters/afbot#1]
Wouldn't it be easier to use their API rather than parsing the html?

Their API for vacant apartments is https://www.afbostader.se/redimo/rest/vacantproducts

**Comment by VictorWinberg** [comment]
E.g: https://github.com/VictorWinberg/magasinet.

**Comment by exoji2e** [comment]
Riiight. Didn't know this existed. 

Well I don't need this project anymore, but I planned rewriting it anyway. Will follow your advice if I do, thanks. :)

**Comment by VictorWinberg** [comment]
Stale 💀
